services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - STORAGE_CONNECTION_STRING
    ports:
      - "8000:8000"
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend

secrets:
  STORAGE_CONNECTION_STRING:
    environment: STORAGE_CONNECTION_STRING
