services:
  dagster-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["dagster-webserver", "-h", "0.0.0.0", "-p", "3000"]
    ports:
      - "3000:3000"
    environment:
      - DAGSTER_HOME=/opt/dagster/dagster_home
      - STORAGE_CONNECTION_STRING=${STORAGE_CONNECTION_STRING}
    volumes:
      - .:/opt/dagster/dagster_home

  dagster-daemon:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["dagster-daemon", "run"]
    environment:
      - DAGSTER_HOME=/opt/dagster/dagster_home
      - STORAGE_CONNECTION_STRING=${STORAGE_CONNECTION_STRING}
    volumes:
      - .:/opt/dagster/dagster_home

volumes:
  dagster_home:
