services:
  dagster-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["dagster-webserver", "-h", "0.0.0.0", "-p", "4000"]
    ports:
      - "4000:4000"
    environment:
      - DAGSTER_HOME=/opt/dagster/dagster_home
      - AZURE_ODBC=${AZURE_ODBC}
    volumes:
      - .:/opt/dagster/dagster_home

  dagster-daemon:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["dagster-daemon", "run"]
    environment:
      - DAGSTER_HOME=/opt/dagster/dagster_home
      - AZURE_ODBC=${AZURE_ODBC}
    volumes:
      - .:/opt/dagster/dagster_home

volumes:
  dagster_home:
