services:
  dagster-webserver:
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - AZURE_ODBC
        - STORAGE_CONNECTION_STRING
    command: ["dagster-webserver", "-h", "0.0.0.0", "-p", "3000"]
    ports:
      - "3000:3000"
    environment:
      - DAGSTER_HOME=/opt/dagster/dagster_home
    volumes:
      - dagster_home:/opt/dagster/dagster_home

  dagster-daemon:
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - AZURE_ODBC
        - STORAGE_CONNECTION_STRING
    command: ["dagster-daemon", "run"]
    environment:
      - DAGSTER_HOME=/opt/dagster/dagster_home
    volumes:
      - dagster_home:/opt/dagster/dagster_home

volumes:
  dagster_home:

secrets:
  azure_odbc:
    external: true
  storage_connection_string:
    external: true
