name: deploy-website

on:
  push:
    branches:
      - main
    paths:
      - site/**
      - .github/**/deploy-website.yml

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SSH (build and deploy)
        uses: appleboy/ssh-action@v1.2.0
        env:
          STORAGE_CONNECTION_STRING: ${{ secrets.STORAGE_CONNECTION_STRING }}
          AZURE_ODBC: ${{ secrets.AZURE_ODBC }}
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          envs: STORAGE_CONNECTION_STRING,AZURE_ODBC
          script: |
            cd ~/popularity-tool-for-anilist/site
            git pull origin main
            docker compose up --build -d
