name: deploy-pipeline

on:
  push:
    branches:
      - main
      - dev
    paths:
      - pipelines/**
      - .github/**/deploy-pipeline.yml

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        working-directory: ./pipelines
        env:
          AZURE_ODBC: ${{ secrets.AZURE_ODBC }}
          STORAGE_CONNECTION_STRING: ${{ secrets.STORAGE_CONNECTION_STRING }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          echo "$AZURE_ODBC" | docker secret create azure_odbc - \
          echo "$STORAGE_CONNECTION_STRING" | docker secret create storage_connection_string - \
          docker compose build

      - name: Push image
        env:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          docker push $username/pipelines:latest
