name: deploy-pipeline

on:
  push:
    branches:
      - main
    paths:
      - pipelines/**
      - .github/**/deploy-pipeline.yml

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SSH (build and deploy)
        uses: appleboy/ssh-action@v1.0.3
        env:
          AZURE_ODBC: ${{ secrets.AZURE_ODBC }}
          STORAGE_CONNECTION_STRING: ${{ secrets.STORAGE_CONNECTION_STRING }}
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          envs: AZURE_ODBC,STORAGE_CONNECTION_STRING
          script: |
            cd ~/popularity-tool-for-anilist/pipelines
            git pull origin main
            docker compose up --build -d
