name: deploy-pipeline

on:
  push:
    branches:
      - main
      - dev
    paths:
      - pipelines/**
      - .github/**/deploy-pipeline.yml

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SSH (build and deploy)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          STORAGE_CONNECTION_STRING: ${{ secrets.STORAGE_CONNECTION_STRING }}
          AZURE_ODBC: ${{ secrets.AZURE_ODBC }}
          script: |
            pwd
            cd ~/popularity-tool-for-anilist/pipelines
            git pull origin dev
            touch .env
            echo STORAGE_CONNECTION_STRING="$STORAGE_CONNECTION_STRING" >> .env
            echo AZURE_ODBC="$AZURE_ODBC" >> .env
