name: deploy-pipeline

on:
  push:
    branches:
      - main
      - dev
    paths:
      - pipelines/**
      - .github/**/deploy-pipeline.yml

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          touch .env
          echo STORAGE_CONNECTION_STRING=${{ secrets.STORAGE_CONNECTION_STRING }} >> .env
          echo AZURE_ODBC=${{ secrets.AZURE_ODBC }} >> .env
          cat .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        working-directory: ./pipelines
        run: |
          docker compose build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        env:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          docker push $username/pipelines:latest
