name: deploy-pipeline

on:
  push:
    branches:
      - main
      - dev
    paths:
      - pipelines/**
      - .github/**/deploy-pipeline.yml

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env file
        env:
          STORAGE_CONNECTION_STRING: ${{ secrets.STORAGE_CONNECTION_STRING }}
          AZURE_ODBC: ${{ secrets.AZURE_ODBC }}
        run: |
          touch .env
          echo STORAGE_CONNECTION_STRING="$STORAGE_CONNECTION_STRING" >> .env
          echo AZURE_ODBC="$AZURE_ODBC" >> .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        working-directory: ./pipelines
        env:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          docker compose build
          docker tag pipelines-dagster-webserver $username/pipelines:webserver
          docker tag pipelines-dagster-daemon $username/pipelines:daemon

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        env:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          docker push "$username"/pipelines:webserver
          docker push "$username"/pipelines:daemon
