name: deploy-pipeline

on:
  push:
    branches:
      - main
      - dev
    paths:
      - pipelines/**
      - .github/**

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:pipelines"
          push: true
          tags: ani/pipelines:latest
          secrets: |
            AZURE_ODBC=${{ secrets.AZURE_ODBC }}
            STORAGE_CONNECTION_STRING=${{ secrets.STORAGE_CONNECTION_STRING }}
