name: lint

on: 
  push:
    branches:
      - dev
    paths:
      - 'site/**'
      - 'pipelines/**'
      - 'pyproject.toml'
      - '.github/workflows/test.yml'
      - '.github/workflows/lint.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'site/**'
      - 'pipelines/**'
      - 'tailwind.config.js'
      - '.github/workflows/test.yml'
      - '.github/workflows/lint.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Black
      uses: psf/black@stable
      with:
        options: "--check --verbose"
        src: "."

    - name: Isort
      uses: isort/isort-action@master
      with:
        sort-path: "."
        requirements-files: "./requirements.txt"
        configuration: "--check-only --diff --profile black"
