name: lint

on: 
  push:
    branches-ignore:
      - main
    paths:
      - 'site/**'
      - 'pipelines/**'
      - 'pyproject.toml'
      - '.github/workflows/test.yml'
      - '.github/workflows/lint.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'site/**'
      - 'pipelines/**'
      - 'tailwind.config.js'
      - '.github/workflows/test.yml'
      - '.github/workflows/lint.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Lint
      uses: astral-sh/ruff-action@v3
      with:
        version: "0.8.6"
        args: "format --check"
        version: "0.8.6"
