name: test

on: 
  push:
    branches-ignore:
      - main
    paths:
      - 'site/**'
      - 'pyproject.toml'
      - '.github/workflows/test.yml'
      - '.github/workflows/lint.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'site/**'
      - 'pyproject.toml'
      - '.github/workflows/test.yml'
      - '.github/workflows/lint.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: |
          uv sync --all-extras --dev

      - name: Run tests
        working-directory: ./site
        env:
          STORAGE_CONNECTION_STRING: ${{ secrets.STORAGE_CONNECTION_STRING }}
          AZURE_ODBC: ${{ secrets.AZURE_ODBC }}
        run: uv run pytest
