name: test

on: 
  push:
    branches:
      - dev
    paths:
      - 'site/**'
      - 'pyproject.toml'
      - '.github/workflows/test.yml'
      - '.github/workflows/lint.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'site/**'
      - 'pyproject.toml'
      - '.github/workflows/test.yml'
      - '.github/workflows/lint.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: ./site
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        working-directory: ./site
        env:
          STORAGE_CONNECTION_STRING: ${{ secrets.STORAGE_CONNECTION_STRING }}
        run: python -m pytest
